[project]
authors = ["Scott Henderson <scottyhq@gmail.com>"]
channels = ["conda-forge", "nodefaults"]
description = "Add a short description here"
name = "default"
platforms = ["osx-arm64", "linux-64"]
version = "0.1.0"

[tasks]
download = "./scripts/download_rainier.py"

[dependencies]
python = ">=3.12,<3.13"
pystac-client = ">=0.8.6,<0.9"
ipykernel = ">=6.29.5,<7"
geopandas = ">=1.0.1,<2"
matplotlib-base = ">=3.10.1,<4"
pip = ">=25.0.1,<26"
rasterio = ">=1.4.3,<2"
matplotlib = ">=3.10.1,<4"
ipython = ">=9.0.2,<10"
xarray = ">=2025.1.2,<2026"
gdal = ">=3.10.2,<4"
sarpy = ">=1.3.59,<2"
pyarrow = "<19"
fsspec = ">=2025.3.0,<2026"
tabulate = ">=0.9.0,<0.10"
rioxarray = ">=0.18.2,<0.19"
cartopy = ">=0.24.0,<0.25"
click = ">=8.1.8,<9"
# waiting for release
#stac-geoparquet = ">=0.6.1,<0.7"


[pypi-dependencies]
spacetrack = ">=1.4.0, <2"
stac-asset = { version = ">=0.4.6, <0.5", extras = ["cli"] }
stac-geoparquet = { git = "https://github.com/stac-utils/stac-geoparquet.git"}
#stac-geoparquet = { path = "/Users/scotthenderson/GitHub/stac-geoparquet", editable = true}
#sarkit = ">=0.1.0, <0.2"
