[project]
authors = ["Scott Henderson <scottyhq@gmail.com>"]
channels = ["conda-forge", "nodefaults"]
description = "Add a short description here"
name = "default"
platforms = ["osx-arm64", "linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
pystac-client = ">=0.8.4,<0.9"
ipykernel = ">=6.29.5,<7"
geopandas = ">=1.0.1,<2"
matplotlib-base = ">=3.9.2,<4"
python = ">=3.11"
pip = "*"
rioxarray = ">=0.17.0,<0.18"
rasterio = "1.3.*"
matplotlib = ">=3.9.2,<4"
ipython = ">=8.28.0,<9"
xarray = ">=2024.9.0,<2025"
gdal = ">=3.9.2,<4"
sarpy = ">=1.3.59,<2"
ipympl = ">=0.9.4,<0.10"
hvplot = ">=0.11.1,<0.12"
holoviews = ">=1.19.1,<2"
aiobotocore = ">=2.15.1,<3"
s3fs = ">=2024.9.0,<2025"
aiohttp = ">=3.10.10,<4"
cloudpathlib = ">=0.20.0,<0.21"
cloudpathlib-s3 = ">=0.20.0,<0.21"
jupyter_bokeh = ">=4.0.5,<5"
jupyterlab = ">=4.2.5,<5"
timezonefinder = ">=6.5.4,<7"
pyarrow = ">=17.0.0,<18"
rio-stac = ">=0.9.0,<0.10"
#stac-geoparquet = ">=0.6.0,<0.7"


[pypi-dependencies]
spacetrack = ">=1.3.1, <2"
stac-asset = ">=0.4.3, <0.5"
stac-geoparquet = { path = "/Users/scotthenderson/GitHub/stac-geoparquet", editable = true}
