[project]
authors = ["Scott Henderson <scottyhq@gmail.com>"]
channels = ["conda-forge", "nodefaults"]
description = "Add a short description here"
name = "default"
platforms = ["osx-arm64", "linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "*"
pystac-client = "*"
ipykernel = "*"
geopandas = "*"
matplotlib-base = "*"
pip = "*"
#rioxarray = ">=0.18.2,<0.19"
rasterio = "*"
matplotlib = "*"
ipython = "*"
xarray = "*"
gdal = "*"
sarpy = "*"
#sarpy = ">=1.3.59,<2"
#ipympl = ">=0.9.6,<0.10"
#hvplot = ">=0.11.2,<0.12"
#holoviews = ">=1.20.0,<2"
#aiobotocore = ">=2.19.0,<3"
#s3fs = ">=2025.2.0,<2026"
#aiohttp = ">=3.11.12,<4"
#cloudpathlib = ">=0.20.0,<0.21"
#cloudpathlib-s3 = ">=0.20.0,<0.21"
#jupyter_bokeh = ">=4.0.5,<5"
#jupyterlab = ">=4.3.5,<5"
#timezonefinder = ">=6.5.8,<7"
pyarrow = "*"
fsspec = ">=2025.2.0,<2026"
tabulate = ">=0.9.0,<0.10"
rioxarray = ">=0.18.2,<0.19"
cartopy = ">=0.24.0,<0.25"
#rio-stac = ">=0.10.1,<0.11"

# [dependencies]
# python = ">=3.12,<3.13"
# pystac-client = ">=0.8.5,<0.9"
# ipykernel = ">=6.29,<7"
# geopandas = ">=1.0.1,<2"
# matplotlib-base = ">=3.10.0,<4"
# pip = ">=25.0.1,<26"
# rioxarray = ">=0.18.2,<0.19"
# rasterio = ">=1.4.3,<2"
# matplotlib = ">=3.10.0,<4"
# ipython = ">=8.31.0,<9"
# xarray = ">=2025.1.2,<2026"
# gdal = ">=3.10.1,<4"
# sarpy = ">=1.3.59,<2"
# ipympl = ">=0.9.6,<0.10"
# hvplot = ">=0.11.2,<0.12"
# holoviews = ">=1.20.0,<2"
# aiobotocore = ">=2.19.0,<3"
# s3fs = ">=2025.2.0,<2026"
# aiohttp = ">=3.11.12,<4"
# cloudpathlib = ">=0.20.0,<0.21"
# cloudpathlib-s3 = ">=0.20.0,<0.21"
# jupyter_bokeh = ">=4.0.5,<5"
# jupyterlab = ">=4.3.5,<5"
# timezonefinder = ">=6.5.8,<7"
# pyarrow = ">=19.0.0,<20"
# rio-stac = ">=0.10.1,<0.11"


[pypi-dependencies]
spacetrack = ">=1.3.1, <2"
stac-asset = ">=0.4.6, <0.5"
stac-geoparquet = { path = "/Users/scotthenderson/GitHub/stac-geoparquet", editable = true}
sarkit = ">=0.1.0, <0.2"
