[project]
authors = ["Scott Henderson <scottyhq@gmail.com>"]
channels = ["conda-forge", "nodefaults"]
description = "Add a short description here"
name = "default"
platforms = ["osx-arm64", "linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
pystac-client = ">=0.8.4,<0.9"
ipykernel = ">=6.29.5,<7"
geopandas = ">=1.0.1,<2"
matplotlib-base = ">=3.9.2,<4"
python = ">=3.11"
pip = "*"

[pypi-dependencies]
spacetrack = ">=1.3.1, <2"
